[package]
name = "gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.95", features = ["full", "extra-traits"] }
clap = { version = "3.1.18", features = ["derive"] }
quote = "1.0.20"
proc-macro2 = "1.0.41"